apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "liftbridge.fullname" . }}
  labels:
    {{- include "liftbridge.labels" . | nindent 4 }}
data:
  liftbridge.yaml: |
    listen: 0.0.0.0:{{ .Values.liftbridge.port }}
    logging.level: {{ .Values.liftbridge.loglevel }}

    nats.servers:
    {{- range .Values.nats }}
      {{- if .auth.enabled }}
      - "nats://{{- .auth.username }}:{{- .auth.password }}@{{- .address }}:{{- .port }}"
      {{- else }}
      - "nats://{{- .address }}:{{- .port }}"
      {{- end }}
    {{- end }}

    clustering.min.insync.replicas: {{ .Values.liftbridge.minInsyncReplicas }}